defmodule JobyKit.NavComponentTest do
  use ExUnit.Case, async: true

  import Phoenix.Component
  import Phoenix.LiveViewTest, only: [rendered_to_string: 1]

  alias JobyKit.NavComponent

  # Every app generated by `mix joby_kit.new` calls simple_nav/1 from its
  # layout, so a render-time crash here means a fresh app boots to an
  # exception page on every route.

  describe "simple_nav" do
    test "carries the wrapper contract's data-component" do
      assigns = %{}
      html = rendered_to_string(~H|<NavComponent.simple_nav />|)

      assert html =~ ~s|data-component="JobyKit.NavComponent.simple_nav"|
      assert html =~ "navbar"
    end

    test "renders the three default links" do
      assigns = %{}
      html = rendered_to_string(~H|<NavComponent.simple_nav />|)

      assert html =~ "Home"
      assert html =~ "Design"
      assert html =~ "Custom Designs"
      assert html =~ ~s|href="/"|
      assert html =~ ~s|href="/design"|
      assert html =~ ~s|href="/custom-designs"|
    end

    test "defaults the brand to JobyKit, pointing at root" do
      assigns = %{}
      html = rendered_to_string(~H|<NavComponent.simple_nav />|)

      assert html =~ "JobyKit"
      assert html =~ "btn btn-ghost"
    end

    test "brand and brand_href are overridable" do
      assigns = %{}

      html =
        rendered_to_string(~H|<NavComponent.simple_nav brand="Orchester" brand_href="/home" />|)

      assert html =~ "Orchester"
      assert html =~ ~s|href="/home"|
      refute html =~ ">JobyKit<"
    end

    test "active marks exactly the matching link" do
      assigns = %{}
      html = rendered_to_string(~H|<NavComponent.simple_nav active="design" />|)

      assert count(html, "menu-active") == 1

      # …and the marker sits on the Design entry, not another one.
      [design_link] =
        Regex.run(~r|<a[^>]*href="/design"[^>]*>|, html)

      assert design_link =~ "menu-active"
    end

    test "no link is active when active is omitted" do
      assigns = %{}
      html = rendered_to_string(~H|<NavComponent.simple_nav />|)

      refute html =~ "menu-active"
    end

    test "an unknown active key simply highlights nothing" do
      assigns = %{}
      html = rendered_to_string(~H|<NavComponent.simple_nav active="nope" />|)

      refute html =~ "menu-active"
    end

    test "links can be replaced wholesale" do
      assigns = %{
        links: [
          %{key: "peers", label: "Peers", href: "/peers"},
          %{key: "jobs", label: "Jobs", href: "/jobs"}
        ]
      }

      html = rendered_to_string(~H|<NavComponent.simple_nav links={@links} active="jobs" />|)

      assert html =~ "Peers"
      assert html =~ "Jobs"
      refute html =~ "Custom Designs"

      [jobs_link] = Regex.run(~r|<a[^>]*href="/jobs"[^>]*>|, html)
      assert jobs_link =~ "menu-active"
    end

    test "an empty link list renders the bar without entries" do
      assigns = %{}
      html = rendered_to_string(~H|<NavComponent.simple_nav links={[]} />|)

      assert html =~ "navbar"
      refute html =~ "<li"
    end

    test "class is additive on the root, not a replacement" do
      assigns = %{}
      html = rendered_to_string(~H|<NavComponent.simple_nav class="sticky top-0" />|)

      assert html =~ "navbar"
      assert html =~ "sticky top-0"
    end
  end

  defp count(haystack, needle), do: length(String.split(haystack, needle)) - 1
end
